services:
  database-devbox:
    image: postgres:17
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aidbox
      POSTGRES_PORT: "5432"
  devbox:
    depends_on:
      - database-devbox
    image: "healthsamurai/aidboxone:2506"
    ports:
      - "8888:8888"
    environment:
      PGHOST: "database-devbox"
      AIDBOX_LICENSE: "${AIDBOX_LICENSE:?err}"
      AIDBOX_CLIENT_ID: "root"
      AIDBOX_CLIENT_SECRET: "secret"
      AIDBOX_ADMIN_ID: "admin"
      AIDBOX_ADMIN_PASSWORD: "secret"
      AIDBOX_PORT: "8888"
      AIDBOX_FHIR_SCHEMA_VALIDATION: false
      AIDBOX_FHIR_VERSION: 4.0.1
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      PGUSER: aidbox
      PGPASSWORD: secret
      PGDATABASE: aidbox
      PGPORT: "5432"
    healthcheck:
      test: "curl -f http://localhost:8888/health"
      interval: 10s
      retries: 12
